---
driver:
  name: ec2
scenario:
  name: travis-aws
platforms:
  - name: aws-ec2-ubuntu
    image_owner: 099720109477
    image_name: ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-*
    instance_type: t2.micro
    vpc_subnet_id: subnet-06400c2e5a812a135
    instance_tags:
      Name: molecule_instance
provisioner:
  name: ansible
  playbooks:
    converge: ./converge.yml
  lint:
    name: ansible-lint
verifier:
  name: testinfra
